name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # You can change 'main' to whatever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu Linux

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the desired Node.js version (e.g., 16, 18)

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Angular app
      - name: Build the app
        run: npm run build --if-present

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy-action@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"  # Root folder of your app (adjust if necessary)
          output_location: "dist/client"  # Replace with the folder where the built files are located (Angular default is `dist/`)

